apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pythonflaskapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pythonflaskapp
    repoURL: https://github.com/isaacam/calculadora-manifiestos-argo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  