apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flask 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask 
  template:
    metadata:
      labels:
        app: flask 
    spec:
      containers:
      - name: isaacam
        image: isaacam/calculadora_app:85a790d91f3b924866c8858ec8863a5971f49c9a
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "localhost"
        - name: REDIS_PORT
          value: "6379"
      - name: redis-final
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: flaskservice
spec:
  selector:
    app: flask
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer