apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
stringData:
  secret-key: "generada-aleatoriamente-reemplazar-en-produccion"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  config.py: |
    import os
    # Configuración básica para tu app Flask
    DEBUG = False
    SECRET_KEY = os.environ.get('SECRET_KEY', 'clave-desarrollo-solo-para-local')
    REDIS_HOST = 'localhost'
    REDIS_PORT = 6379
    # Añade aquí otras configuraciones específicas que necesite tu app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flask 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask 
  template:
    metadata:
      labels:
        app: flask 
    spec:
      containers:
      - name: flask-app
        image: isaacam/calculadora_app:41e3f3364c434a45e54e7c1fc4503f90cb035387
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: secret-key
        - name: REDIS_HOST
          value: "localhost"
        - name: REDIS_PORT
          value: "6379"
        volumeMounts:
        - name: config-volume
          mountPath: /app/app/app/config.py
          subPath: config.py
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config-volume
        configMap:
          name: flask-config
---
apiVersion: v1
kind: Service
metadata:
  name: flaskservice
spec:
  selector:
    app: flask
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer